// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/did.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Did struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Did) Reset()         { *m = Did{} }
func (m *Did) String() string { return proto.CompactTextString(m) }
func (*Did) ProtoMessage()    {}
func (*Did) Descriptor() ([]byte, []int) {
	return fileDescriptor_e27271dd16672939, []int{0}
}

func (m *Did) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Did.Unmarshal(m, b)
}
func (m *Did) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Did.Marshal(b, m, deterministic)
}
func (m *Did) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Did.Merge(m, src)
}
func (m *Did) XXX_Size() int {
	return xxx_messageInfo_Did.Size(m)
}
func (m *Did) XXX_DiscardUnknown() {
	xxx_messageInfo_Did.DiscardUnknown(m)
}

var xxx_messageInfo_Did proto.InternalMessageInfo

func (m *Did) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Did) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func init() {
	proto.RegisterType((*Did)(nil), "did.Did")
}

func init() { proto.RegisterFile("protos/did.proto", fileDescriptor_e27271dd16672939) }

var fileDescriptor_e27271dd16672939 = []byte{
	// 149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0x4f, 0xc9, 0x4c, 0xd1, 0x03, 0x33, 0x85, 0x98, 0x53, 0x32, 0x53, 0x94, 0x34,
	0xb9, 0x98, 0x5d, 0x32, 0x53, 0x84, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35,
	0x38, 0x83, 0x98, 0x32, 0x53, 0x84, 0x84, 0xb8, 0x58, 0x52, 0x52, 0x8b, 0x93, 0x25, 0x98, 0xc0,
	0x22, 0x60, 0xb6, 0x91, 0x36, 0x17, 0x67, 0x70, 0x66, 0x6e, 0x41, 0x4e, 0x2a, 0x48, 0x83, 0x1c,
	0x17, 0x9b, 0x7b, 0x6a, 0x09, 0x88, 0xc5, 0xa1, 0x07, 0x32, 0xd2, 0x25, 0x33, 0x45, 0x0a, 0xce,
	0x52, 0x62, 0x70, 0x52, 0x8f, 0x52, 0x4d, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf,
	0xd5, 0x4f, 0xce, 0xcf, 0xcd, 0xcb, 0x4c, 0x06, 0x5b, 0xae, 0x9b, 0x5a, 0x91, 0x08, 0x32, 0x44,
	0x1f, 0xe2, 0x9e, 0x24, 0x36, 0x30, 0x6d, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xc1, 0x3d, 0xec,
	0xea, 0xa0, 0x00, 0x00, 0x00,
}
